<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>App</AssemblyName>
    <RootNamespace>Atlas.Example.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <ProjectReference Include="../lib/Lib.csproj" />
    <ProjectReference Include="../../../../src/tools/cs/atlas-cs-cli/Atlas.Cs.Cli.csproj" ReferenceOutputAssembly="false">
      <SetConfiguration>Configuration=$(Configuration)</SetConfiguration>
    </ProjectReference>
  </ItemGroup>
  <Import Project="../../../../src/tools/cs/atlas-cs-msbuild/build/StarCruiseStudios.Atlas.Cs.MSBuild.targets" />
</Project>
