<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackageId>Atlas.Example.App</PackageId>
    <AssemblyName>Atlas.Example.App</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Application/Atlas.Example.Application.csproj" />
    <ProjectReference Include="../Domain/Atlas.Example.Domain.csproj" />
    <ProjectReference Include="../Infrastructure/Atlas.Example.Infrastructure.csproj" />
  </ItemGroup>
</Project>

