# frozen_string_literal: true

source "https://rubygems.org"

gem "starcruisestudios-atlas-rb-cli", path: "atlas-rb-cli"
gem "starcruisestudios-atlas-rb-rake", path: "atlas-rb-rake"
gem "starcruisestudios-atlas-rb-sdk", path: "atlas-rb-sdk"

gem "minitest", "~> 5.18"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.75", require: false
