# frozen_string_literal: true

require "atlas/rb/rake"

Atlas::Rake.configure do |atlas|
  atlas.root_directory = "../../architecture"
  atlas.gemspec_file = "atlas-example-lib.gemspec"
  atlas.source_roots = ["lib"]
  atlas.route_files = []
  atlas.generate_on_build = false
end
