# frozen_string_literal: true

require "atlas/rb/rake"

Atlas::Rake.configure do |atlas|
  atlas.model_file = "../../architecture/models/app.atlas.module.yml"
  atlas.gemspec_file = "atlas-example-app.gemspec"
  atlas.source_roots = ["lib"]
  atlas.route_files = []
  atlas.generate_on_build = false
end
