<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Lib</AssemblyName>
    <RootNamespace>Atlas.Example.Lib</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <ProjectReference Include="../../../../src/tools/cs/atlas-cs-cli/Atlas.Cs.Cli.csproj" ReferenceOutputAssembly="false">
      <SetConfiguration>Configuration=$(Configuration)</SetConfiguration>
    </ProjectReference>
  </ItemGroup>
  <Import Project="../../../../src/tools/cs/atlas-cs-msbuild/build/StarCruiseStudios.Atlas.Cs.MSBuild.targets" />
</Project>
